baseurl = "https://influxdata.github.io/branding/"
languageCode = "en-us"
title = "InfluxData Branding Docs"
publishDir= "../docs"
canonifyURLs = true

[[menu.main]]
	name = "Logo"
	identifier = "logo"
	weight = 0
	url = "/logo/"
	pre = "cubo-uniform"
[[menu.main]]
	name = "Colors"
	identifier = "colors"
	weight = 10
	url = "/colors/"
	pre = "brush"
[[menu.main]]
	name = "Typography"
	identifier = "typography"
	weight = 20
	url = "/typography/"
	pre = "alpha-a"
[[menu.main]]
	name = "Images & Artwork"
	identifier = "artwork"
	weight = 30
	url = "/artwork/"
	pre = "polaroid"
[[menu.main]]
	name = "Presentations"
	identifier = "presentations"
	weight = 40
	url = "/presentations/"
	pre = "keynote"
[[menu.main]]
	name = "Misc"
	identifier = "misc"
	weight = 50
	url = "/misc/"
	pre = "triangle"