baseurl = "https://influxdata.github.io/branding/"
languageCode = "en-us"
title = "InfluxData Branding Docs"
publishDir= "../docs"
canonifyURLs = true

[[menu.main]]
	name = "Brand"
	identifier = "brand"
	weight = 1
	url = "/brand/"
	pre = "eye"
[[menu.main]]
	name = "Logo"
	identifier = "logo"
	weight = 10
	url = "/logo/"
	pre = "cubo-uniform"
[[menu.main]]
	name = "Visual Assets"
	identifier = "visual"
	weight = 20
	url = "/visual/"
	pre = "polaroid"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true