baseurl = "https://influxdata.github.io/branding/"
languageCode = "en-us"
title = "InfluxData Branding Docs"
publishDir= "../docs"
canonifyURLs = true

[[menu.main]]
	name = "Brand"
	identifier = "brand"
	weight = 1
	url = "/brand/"
	pre = "eye"
[[menu.main]]
	name = "Logo"
	identifier = "logo"
	weight = 10
	url = "/logo/"
	pre = "cubo-uniform"
[[menu.main]]
	name = "Typography"
	identifier = "typography"
	weight = 20
	url = "/typography/"
	pre = "alpha-a"
[[menu.main]]
	name = "Misc"
	identifier = "misc"
	weight = 50
	url = "/misc/"
	pre = "triangle"
